name:                muste-ajax
version:             0.4.0
license:             Artistic-2.0
license-file:        LICENSE
maintainer:
  - Herbert Lange <herbert.lange@cse.gu.se>
  - Peter Ljunglöf <peter.ljunglof@cse.gu.se>
copyright:
  - (c) 2017-2019 Herbert Lange
  - (c) 2018-2019 Peter Ljunglöf
  - (c) 2018      Frederik Hanghøj Iversen

synopsis:            Multimodal semantics in Text editing (web server + API)
category:            Web

source-dirs:
  - src/

dependencies:
  - base                 >= 4.11.1.0 && < 4.13
  - aeson                >= 1.3.1.1  && < 1.5   # Data.Aeson
  - binary               >= 0.8.5.1  && < 0.9   # Data.Binary
  - bytestring           >= 0.10.8.2 && < 0.11  # Data.ByteString
  - containers           >= 0.5.11.0 && < 0.7   # Data.{Map, Set, Tree, ...}
  - cryptonite           >= 0.25     && < 0.26  # Crypto
  - direct-sqlite        >= 2.3.23   && < 2.4   # Database.SQLite3
  - directory            >= 1.3.1.5  && < 1.4   # System.Directory
  - exceptions           >= 0.10.0   && < 0.11  # Control.Monad.Catch
  - file-embed           >= 0.0.10.1 && < 0.1   # Data.FileEmbed
  - filepath             >= 1.4.2    && < 1.5   # System.FilePath
  - gitrev               >= 1.3.1    && < 1.4   # Development.GitRev
  - io-streams           >= 1.5.0.1  && < 1.6   # System.IO.Streams
  - lens                 >= 4.16.1   && < 4.18  # Control.Lens, ...
  - lifted-base          >= 0.2.3.12 && < 0.3   # Control.Exception.Lifted
  - monad-control        >= 1.0.2.3  && < 1.1   # Control.Monad.Trans.Control
  - mtl                  >= 2.2.2    && < 2.3   # Control.Monad.{Except, Reader, State, Trans, ...}
  - muste                >= 0.4      && < 0.5   # Muste
  - optparse-applicative >= 0.14.3.0 && < 0.15  # Options.Applicative
  - QuickCheck           >= 2.11.3   && < 2.12  # Test.QuickCheck
  - snap                 >= 1.1.2.0  && < 1.2   # Snap, Snap.Snaplet
  - snap-core            >= 1.0.3.2  && < 1.1   # Snap.{Core, Types, Util, ...}
  - sqlite-simple        >= 0.4.16.0 && < 0.5   # Database.SQLite.Simple
  - text                 >= 1.2.3.1  && < 1.3   # Data.Text
  - time                 >= 1.8.0.2  && < 1.9   # Data.Time
  - transformers-base    >= 0.4.5.2  && < 0.5   # Control.Monad.Base
  - unordered-containers >= 0.2.9.0  && < 0.3   # Data.HashMap
  - vector               >= 0.12.0.1 && < 0.13  # Data.Vector
  - yaml                 >= 0.8.32   && < 0.12  # Data.Yaml

executable:
  main: Main.hs

  other-modules:
    - Muste.Web.Class
    - Muste.Web.Config
    - Muste.Web.DbInit
    - Muste.Web.Handlers.Session
    - Muste.Web.Handlers.Results
    - Muste.Web.Handlers.Grammar
    - Muste.Web.Protocol
    - Options
