name:                muste-ajax
version:             0.2.3.1
license-file:        LICENSE
author:              Herbert Lange
maintainer:          herbert.lange@cse.gu.se

category:            Web

flags:
  CGI:
    description: Build as a CGI program
    manual: true
    default: false

# ghc-options: -fmax-valid-substitutions=0

data-files:
  - ./static/index.html
  - ./static/img/menu.jpg
  - ./static/img/menu2.jpg
  - ./static/img/menu1.jpg
  - ./static/img/congrats.jpg
  - ./static/img/unfinished.jpg
  - ./static/img/finished.jpg
  - ./static/img/logout.jpg
  - ./static/img/statistics.jpg
  - ./static/img/exercise.jpg
  - ./static/img/lessonlist.jpg
  - ./static/img/disabled.jpg
  - ./static/jquery-1.11.1.min.js
  - ./static/muste-gui.js
  - ./static/instructions.html
  - ./static/favicon.ico
  - ./static/muste.css

default-extensions:
- UnicodeSyntax
- NamedWildCards
- TypeSynonymInstances
- FlexibleInstances
- ScopedTypeVariables
- ViewPatterns
- DeriveGeneric
- LambdaCase
- TypeApplications
- StandaloneDeriving
- GADTs
- GeneralizedNewtypeDeriving
- TypeFamilies

dependencies:
  - base >= 4.8 && < 4.12
  - aeson >=1.0
  - text
  - bytestring
  - containers
  - muste
  - pgf >= 3.9.1
  - mtl
  - network-uri
  - filepath
  - vector
  - time
  - base64-bytestring
  - cryptonite
  - crypto-random-api
  - wai
  - warp
  - http-types
  - sqlite-simple >= 0.4.16.1
  - QuickCheck
  - snap
  - snap-core
  - snap-server
  - snap-extras
  - lens
  - io-streams
  - exceptions
  - yaml
  - template-haskell
  - directory
  - direct-sqlite
  - file-embed
  - optparse-applicative
  - prettyprinter

library:

  source-dirs:
    - src

  exposed-modules:
    - Ajax
    - Database
    - Database.Types
    - Config
    - Config.TH
    - Protocol

  other-modules:
    - Paths_muste_ajax

executable:
  source-dirs:
    - app

  main: Main.hs

  dependencies:
    - muste-ajax
