name:                muste-ajax
version:             0.2.4.0
license-file:        LICENSE
author:              Herbert Lange
maintainer:          herbert.lange@cse.gu.se

category:            Web

flags:
  CGI:
    description: Build as a CGI program
    manual: true
    default: false

ghc-options: -fmax-valid-substitutions=0

default-extensions:
- LambdaCase
- OverloadedStrings
- TypeApplications
- ViewPatterns
- FlexibleContexts
- StandaloneDeriving
- TupleSections
- UnicodeSyntax
- ConstraintKinds

data-files:
  - ./static/index.html
  - ./static/img/menu.jpg
  - ./static/img/menu2.jpg
  - ./static/img/menu1.jpg
  - ./static/img/congrats.jpg
  - ./static/img/unfinished.jpg
  - ./static/img/finished.jpg
  - ./static/img/logout.jpg
  - ./static/img/statistics.jpg
  - ./static/img/exercise.jpg
  - ./static/img/lessonlist.jpg
  - ./static/img/disabled.jpg
  - ./static/jquery-1.11.1.min.js
  - ./static/muste-gui.js
  - ./static/instructions.html
  - ./static/favicon.ico
  - ./static/muste.css

default-extensions:
- UnicodeSyntax
- NamedWildCards
- TypeSynonymInstances
- FlexibleInstances
- ScopedTypeVariables
- ViewPatterns
- DeriveGeneric
- LambdaCase
- TypeApplications
- StandaloneDeriving
- GADTs
- GeneralizedNewtypeDeriving
- TypeFamilies

dependencies:
- QuickCheck           >= 2.9.2    && < 2.12
- aeson                >= 1.1.2.0  && < 1.4
- base                 >= 4.9.1.0  && < 4.12
- base64-bytestring    >= 1.0.0.1  && < 1.1
- bytestring           >= 0.10.8.1 && < 0.11
- containers           >= 0.5.7.1  && < 0.6
- crypto-random-api    >= 0.2.0    && < 0.3
- cryptonite           >= 0.23     && < 0.26
- direct-sqlite        >= 2.3.21   && < 2.4
- directory            >= 1.3.0.0  && < 1.4
- exceptions           >= 0.8.3    && < 0.11
- file-embed           >= 0.0.10   && < 0.1
- filepath             >= 1.4.1.1  && < 1.5
- http-types           >= 0.9.1    && < 0.13
- io-streams           >= 1.4.1.0  && < 1.6
- lens                 >= 4.15.4   && < 4.17
- mtl                  >= 2.2.1    && < 2.3
- muste                >= 0.2.3.1  && < 0.3
- network-uri          >= 2.6.1.0  && < 2.7
- optparse-applicative >= 0.13.2.0 && < 0.15
- pgf                  >= 3.9.1    && < 3.10
- prettyprinter        >= 1.1.1    && < 1.3
- snap                 >= 1.1.1.0  && < 1.2
- snap-core            >= 1.0.3.1  && < 1.1
- snap-extras          >= 0.12.2.0 && < 0.13
- snap-server          >= 1.0.3.3  && < 1.2
- sqlite-simple        >= 0.4.16.1 && < 0.5
- template-haskell     >= 2.11.1.0 && < 2.14
- text                 >= 1.2.2.2  && < 1.3
- time                 >= 1.6.0.1  && < 1.9
- vector               >= 0.12.0.1 && < 0.13
- wai                  >= 3.2.1.1  && < 3.3
- warp                 >= 3.2.13   && < 3.3
- yaml                 >= 0.8.25   && < 0.9
- gitrev

library:
  default-extensions:
  - LambdaCase
  - ScopedTypeVariables
  - OverloadedStrings
  - TypeApplications
  - ViewPatterns
  - FlexibleContexts
  - StandaloneDeriving
  - TupleSections
  - UnicodeSyntax
  - ConstraintKinds

  source-dirs:
    - src

  exposed-modules:
    - Ajax
    - Database
    - Database.Types
    - Config
    - Config.TH
    - Protocol
    - Common

  other-modules:
    - Paths_muste_ajax

executable:
  source-dirs:
    - app

  main: Main.hs

  dependencies:
    - muste-ajax
