name:                muste-ajax
version:             0.2.0.5
license-file:        LICENSE
author:              Herbert Lange
maintainer:          herbert.lange@cse.gu.se

category:            Web

flags:
  CGI:
    description: Build as a CGI program
    manual: true
    default: false

# ghc-options: -fmax-valid-substitutions=0

data-files:
  - ./data/gf/grammars/novo_modo/*.pgf
  - ./log/*.log
  - ./static/index.html
  - ./static/muste.html
  - ./static/cgi-simulation/muste-backend.js
  - ./static/cgi-simulation/prima.js
  - ./static/cgi-simulation/GF.js
  - ./static/muste-haste.css
  - ./static/muste-haste.html
  - ./static/img/menu.jpg
  - ./static/img/menu2.jpg
  - ./static/img/menu1.jpg
  - ./static/img/congrats.jpg
  - ./static/img/unfinished.jpg
  - ./static/img/finished.jpg
  - ./static/img/logout.jpg
  - ./static/img/statistics.jpg
  - ./static/img/exercise.jpg
  - ./static/img/lessonlist.jpg
  - ./static/img/disabled.jpg
  - ./static/jquery-1.11.1.min.js
  - ./static/muste-gui.js
  - ./static/instructions.html
  - ./static/favicon.ico
  - ./static/muste.css

# Relative paths disables Haskell's resource file mechanism. All paths
# are resolved locally to where the `stack exec` command is executed.
# See module `Config`.
cpp-options: -DRELATIVE_PATHS

dependencies:
  - base >= 4.8 && < 4.12
  - aeson >=1.0
  - text
  - bytestring
  - containers
  - muste
  - pgf
  - mtl
  - network-uri
  - filepath
  - vector
  - time
  - base64-bytestring
  - cryptonite
  - crypto-random-api
  - wai
  - warp
  - http-types
  - sqlite-simple >= 0.4.16.1
  - QuickCheck
  - snap
  - snap-core
  - snap-server
  - snap-extras
  - lens
  - io-streams
  - exceptions

library:

  source-dirs:
    - src

  exposed-modules:
    - Ajax
    - Database
    - Database.Types
    - Config
    - Protocol

  other-modules:
    - Paths_muste_ajax

executables:
  muste-ajax:
    source-dirs:
      - muste-ajax

    main: Main.hs

    # when:
    #   - condtion: flag(CGI)
    #     then:
    #       main:             Main-CGI.hs
    #     else:
    #       main:             Main-Standalone.hs

    # when:
    #   - condition: flag(CGI)
    #     then:
    #       dependencies:       cgi >= 3001.3.0.2
    #     else:

    dependencies:
      - muste-ajax

  # Commented out because cgi is currently incompatible with lts-12.0

  muste-cgi:
    source-dirs:
      - muste-cgi

    main: Main.hs

    dependencies:
      - muste-ajax
      - cgi >= 3001.3.0.2

  db-init:
    source-dirs:
      - db-init

    main: Main.hs

    other-modules:
      - Data
      - Paths_muste_ajax

    dependencies:
      - muste-ajax
