env:
  browser: true
extends: 'eslint:recommended'
parser: 'babel-eslint'
parserOptions:
  ecmaVersion: 5
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console: off
