name:                muste
version:             0.2.0.1
license:             BSD3
author:              Herbert Lange
maintainer:          herbert.lange@cse.gu.se

synopsis:            Multimodal semantics in Text editing
category:            Text

flags:
  hastePGF:
    description: Build test suite
    manual: true
    default: false

source-dirs:
- src/

dependencies:
- base >= 4.8
- sqlite-simple
- containers >= 0.5
- aeson
- mtl
- aeson
- pgf >=3.7
- binary
- text
- bytestring
- base64-bytestring
- tostring
- prettyprinter
- mono-traversable
- base >=4.8

library:
  other-extensions:
    FlexibleInstances

  dependencies:
    - pgf >=3.7

  exposed-modules:
    - Muste
    - Muste.Tree
    - Muste.Grammar
    - Muste.Feat
    - Muste.Prune
    - Muste.Linearization

  other-modules:
    - Muste.Common
    - Muste.Tree.Internal
    - Muste.Grammar.Internal
    - Muste.Linearization.Internal
    - Muste.AdjunctionTrees

tests:
  test:
    source-dirs:
      - test/
    main:
      Test.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - muste
    - tasty
    - QuickCheck
    - HUnit
    - tasty-hunit
    - tasty-quickcheck
