name:                muste
version:             0.2.6.0
license:             BSD3
author:              Herbert Lange
maintainer:          herbert.lange@cse.gu.se

synopsis:            Multimodal semantics in Text editing
category:            Text

flags:
  hastePGF:
    description: Build test suite
    manual: true
    default: false
  dist:
    description: Build the distribution version
    manual: true
    default: false

source-dirs:
- src/

dependencies:
- aeson              >= 1.1.2.0  && < 1.4
- base               >= 4.9.1.0  && < 4.12
- base64-bytestring  >= 1.0.0.1  && < 1.1
- binary             >= 0.8.3.0  && < 0.9
- bytestring         >= 0.10.8.1 && < 0.11
- containers         >= 0.5.7.1  && < 0.6
- exceptions         >= 0.8.3    && < 0.11
- file-embed         >= 0.0.10   && < 0.1
- filepath           >= 1.4.1.1  && < 1.5
- mono-traversable   >= 1.0.6.0  && < 1.1
- mtl                >= 2.2.1    && < 2.3
- pgf                >= 3.9.1    && < 3.10
- prettyprinter      >= 1.1.1    && < 1.3
- sqlite-simple      >= 0.4.16.1 && < 0.5
- string-conversions >= 0.4.0.1  && < 0.5
- template-haskell   >= 2.11.1.0 && < 2.14
- text               >= 1.2.2.2  && < 1.3
- tostring           >= 0.2.1.1  && < 0.3
- array
- vector
- deepseq
- multiset
- directory
- monad-control
- transformers-base
- snap

when:
  - condition: flag(dist)
    ghc-options:
      - -Wall
      - -Wno-name-shadowing
      - -Werr

ghc-options: -fmax-valid-substitutions=0

default-extensions:
- UnicodeSyntax
- NamedWildCards
- TypeSynonymInstances
- FlexibleInstances
- FlexibleContexts
- ScopedTypeVariables
- ViewPatterns
- DeriveGeneric
- LambdaCase
- TypeApplications
- StandaloneDeriving
- GADTs
- GeneralizedNewtypeDeriving
- TypeFamilies
- MultiParamTypeClasses
- DerivingStrategies

library:
  exposed-modules:
    - Muste
    - Muste.Tree
    - Muste.Grammar
    - Muste.Linearization
    - Muste.Menu
    - Muste.Sentence
    - Muste.Sentence.Annotated
    - Muste.Sentence.Unannotated
    - Muste.Prelude

  other-modules:
    - Muste.Common
    - Muste.Common.SQL
    - Muste.Tree.Internal
    - Muste.Grammar.Internal
    - Muste.Linearization.Internal
    - Muste.AdjunctionTrees
    - Muste.AdjunctionTrees.Internal
    - Muste.Data
    - Muste.Menu.Internal
    - Muste.Selection
    - Muste.Prune
    - Muste.Feat
    - Muste.Util
    - Muste.Sentence.Class
    - Muste.Sentence.Language
    - Muste.Sentence.Linearization
    - Muste.Sentence.Token
    - Muste.Sentence.Token.Class

executables:
  muste:
    source-dirs:
      - app

    main: Main.hs

    dependencies:
      - muste
      - haskeline
      - repline
      - optparse-applicative
      - gitrev

tests:
  test:
    source-dirs:
      - test/
    main:
      Test.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

    dependencies:
    - muste
    - tasty
    - QuickCheck
    - HUnit
    - tasty-hunit
    - tasty-quickcheck

benchmarks:
  benchmark:
    main: Main.hs
    source-dirs: benchmark/
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - muste
      - criterion
