name:                muste
version:             0.2.0.1
license:             BSD3
author:              Herbert Lange
maintainer:          herbert.lange@cse.gu.se

synopsis:            Multimodal semantics in Text editing
category:            Text

flags:
  hastePGF:
    description: Build test suite
    manual: true
    default: false

source-dirs:
  - src/

library:
  other-extensions:    FlexibleInstances

  dependencies:
    - base >=4.8
    - pgf >=3.7
    - QuickCheck >= 2.8
    - containers >= 0.5
    - aeson
    - mtl
    - aeson
    - pgf >=3.7
    - binary
    - text
    - bytestring
    - base64-bytestring
    - sqlite-simple
    - tostring

  exposed-modules:
    - Muste
    - Muste.Tree
    - Muste.Grammar
    - Muste.Feat
    - Muste.Prune
    - Muste.Linearization

  other-modules:
    - Muste.Common
    - Muste.Tree.Internal
    - Muste.Grammar.Internal
    - Muste.Linearization.Internal

# Retired for now.
# fredefox [2018-07-20]
#
# tests:
#   foo-test:
#     source-dirs:
#       - test/
#     main:                Test.hs
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - muste
