name:                muste
version:             0.4.0
license:             BSD3
license-file:        LICENSE
maintainer:
  - Herbert Lange <herbert.lange@cse.gu.se>
  - Peter Ljunglöf <peter.ljunglof@cse.gu.se>
copyright:
  - (c) 2017-2019 Herbert Lange
  - (c) 2018-2019 Peter Ljunglöf
  - (c) 2018      Frederik Hanghøj Iversen

synopsis:            Multimodal semantics in Text editing (base library)
category:            Text

source-dirs:
  - src/

dependencies:
  - base               >= 4.11.1.0 && < 4.13
  - aeson              >= 1.3.1.1  && < 1.5   # Data.Aeson
  - array              >= 0.5.2.0  && < 0.6   # Data.Array
  - binary             >= 0.8.5.1  && < 0.9   # Data.Binary
  - bytestring         >= 0.10.8.2 && < 0.11  # Data.ByteString
  - containers         >= 0.5.11.0 && < 0.7   # Data.{Map, Set, Tree, ...}
  - deepseq            >= 1.4.3.0  && < 1.5   # Control.DeepSeq
  - exceptions         >= 0.10.0   && < 0.11  # Control.Monad.Catch
  - monad-control      >= 1.0.2.3  && < 1.1   # Control.Monad.Trans.Control
  - mono-traversable   >= 1.0.9.0  && < 1.1   # Data.{Containers, MonoTraversable, ...}
  - mtl                >= 2.2.2    && < 2.3   # Control.Monad.{Except, Reader, State, Trans, ...}
  - multiset           >= 0.3.4    && < 0.4   # Data.MultiSet
  - pgf                >= 3.10     && < 3.11  # PGF
  - prettyprinter      >= 1.2.1    && < 1.3   # Data.Text.Prettyprint
  - snap               >= 1.1.2.0  && < 1.2   # Snap, Snap.Snaplet
  - sqlite-simple      >= 0.4.16.0 && < 0.5   # Database.SQLite.Simple
  - string-conversions >= 0.4.0.1  && < 0.5   # Data.String.Conversions
  - text               >= 1.2.3.1  && < 1.3   # Data.Text
  - tostring           >= 0.2.1.1  && < 0.3   # Data.String.ToString
  - transformers-base  >= 0.4.5.2  && < 0.5   # Control.Monad.Base
  - vector             >= 0.12.0.1 && < 0.13  # Data.Vector

library:
  exposed-modules:
    - Muste.AdjunctionTrees
    - Muste.Tree
    - Muste.Grammar
    - Muste.Linearization
    - Muste.Menu
    - Muste.Selection
    - Muste.Sentence
    - Muste.Sentence.Annotated
    - Muste.Sentence.Unannotated
    - Muste.Util

  other-modules:
    - Muste.Tree.Internal
    - Muste.Grammar.Internal
    - Muste.Linearization.Internal
    - Muste.AdjunctionTrees.Internal
    - Muste.Menu.Internal
    - Muste.Prune
    - Muste.Sentence.Class
    - Muste.Sentence.Language
    - Muste.Sentence.Linearization
    - Muste.Sentence.Token
    - Muste.Sentence.Token.Class
