name:                muste
version:             0.2.8.1
license:             BSD3
license-file:        LICENSE
maintainer:
  - Herbert Lange <herbert.lange@cse.gu.se>
  - Peter Ljunglöf <peter.ljunglof@cse.gu.se>
copyright:
  - (c) 2017-2019 Herbert Lange
  - (c) 2018-2019 Peter Ljunglöf
  - (c) 2018      Frederik Hanghøj Iversen

synopsis:            Multimodal semantics in Text editing
category:            Text

flags:
  hastePGF:
    description: Build test suite
    manual: true
    default: false
  dist:
    description: Build the distribution version
    manual: true
    default: false

source-dirs:
  - src/

dependencies:
  - aeson              >= 1.3.1.1  && < 1.5
  - base               >= 4.11.1.0 && < 4.13
  - base64-bytestring  >= 1.0.0.1  && < 1.1
  - binary             >= 0.8.5.1  && < 0.9
  - bytestring         >= 0.10.8.2 && < 0.11
  - containers         >= 0.5.11.0 && < 0.7
  - exceptions         >= 0.10.0   && < 0.11
  - file-embed         >= 0.0.10.1 && < 0.1
  - filepath           >= 1.4.2    && < 1.5
  - mono-traversable   >= 1.0.9.0  && < 1.1
  - mtl                >= 2.2.2    && < 2.3
  - pgf                >= 3.10     && < 3.11
  - prettyprinter      >= 1.2.1    && < 1.3
  - sqlite-simple      >= 0.4.16.0 && < 0.5
  - string-conversions >= 0.4.0.1  && < 0.5
  - template-haskell   >= 2.13.0.0 && < 2.15
  - text               >= 1.2.3.1  && < 1.3
  - tostring           >= 0.2.1.1  && < 0.3
  - array              >= 0.5.2.0  && < 0.6
  - vector             >= 0.12.0.1 && < 0.13
  - deepseq            >= 1.4.3.0  && < 1.5
  - multiset           >= 0.3.4    && < 0.4
  - directory          >= 1.3.1.5  && < 1.4
  - monad-control      >= 1.0.2.3  && < 1.1
  - transformers-base  >= 0.4.5.2  && < 0.5
  - snap               >= 1.1.2.0  && < 1.2
  - yaml               >= 0.8.32   && < 0.12
  - time               >= 1.8.0.2  && < 1.9
  - gitrev             >= 1.3.1    && < 1.4

when:
  - condition: flag(dist)
    ghc-options:
      - -Wall
      - -Wno-name-shadowing
      - -Werr

library:
  exposed-modules:
    - Muste.Tree
    - Muste.Grammar
    - Muste.Linearization
    - Muste.Menu
    - Muste.Sentence
    - Muste.Sentence.Annotated
    - Muste.Sentence.Unannotated
    # FIXME Perhaps a seperate module for these helper?
    - Muste.Prelude
    - Muste.Prelude.Extra
    - Muste.Prelude.SQL
    - Muste.Prelude.Unsafe

  other-modules:
    - Muste.Tree.Internal
    - Muste.Grammar.Internal
    - Muste.Linearization.Internal
    - Muste.AdjunctionTrees
    - Muste.AdjunctionTrees.Internal
    - Muste.Menu.Internal
    - Muste.Selection
    - Muste.Prune
    - Muste.Feat
    - Muste.Util
    - Muste.Sentence.Class
    - Muste.Sentence.Language
    - Muste.Sentence.Linearization
    - Muste.Sentence.Token
    - Muste.Sentence.Token.Class
    - Muste.Prelude.ReExports

custom-setup:
  dependencies:
    - base
    - Cabal
    - turtle
    - text

executables:
  muste-cli:
    source-dirs:
      - app

    main: Main.hs

    dependencies:
      - muste
      - haskeline            >= 0.7.4.3  && < 0.8
      - repline              >= 0.1.7.0  && < 0.3
      - optparse-applicative >= 0.14.3.0 && < 0.15

tests:
  test:
    source-dirs:
      - test/
    main:
      Test.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

    dependencies:
    - muste
    - tasty
    - QuickCheck
    - HUnit
    - tasty-hunit
    - tasty-quickcheck

benchmarks:
  benchmark:
    main: Main.hs
    source-dirs: benchmark/
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - muste
      - criterion
