# This is an example of how to edit an imperative programming
# language. Note that the "source" sentence is hidden, so it's just
# a toy proof-of-concept that the MUSTE technique could be used for
# learning programming.

lessons: lessons-programming.yaml
db: data/programming.sqlite3
access-log: log/access-programming.log
error-log: log/error-programming.log
static-dir: ../muste-ajax/static
port: 8080
users:
  - name: guest
    password: guest
    enabled: yes
