# This is an example of how to edit an imperative programming
# language. Note that the "source" sentence is hidden, so it's just
# a toy proof-of-concept that the MUSTE technique could be used for
# learning programming.

grammars:
  - name: "Imperative"
    path: "grammars/programming/Imperative.pgf"
    options:
      search-size: 7

lessons: lessons-programming.yaml
db: data/programming.sqlite3
access-log: data/programming-access.log
error-log: data/programming-error.log
static-dir: ../muste-ajax/static
port: 8080

users:
  - name: guest
    pwd: guest
