# This is an example of multilingual lessons,
# consisting of five lessons with 2-4 exercises in each.

grammars:
  - name: "Exemplum"
    path: "grammars/exemplum/Exemplum.pgf"
    options:
      search-size: 7

  - name: "ExemplumAlt"
    path: "grammars/exemplum/Exemplum.pgf"
    options:
      search-size: 5

  - name: "Imperative"
    path: "grammars/programming/Imperative.pgf"
    options:
      search-size: 7

courses: 
  - name: "Swedish"
    path: lessons-swedish.yaml
  - name: "Other languages"
    path: lessons-otherlangs.yaml
  - name: "Programming"
    path: lessons-programming.yaml

db: data/mulle.sqlite3
access-log: data/mulle-access.log
error-log: data/mulle-error.log
static-dir: ../muste-ajax/static
port: 8080

users:
  - name: guest
    pwd: guest

