name:                muste-cli
version:             0.3.0
license:             BSD3
license-file:        LICENSE
maintainer:
  - Herbert Lange <herbert.lange@cse.gu.se>
  - Peter Ljunglöf <peter.ljunglof@cse.gu.se>
copyright:
  - (c) 2017-2019 Herbert Lange
  - (c) 2018-2019 Peter Ljunglöf
  - (c) 2018      Frederik Hanghøj Iversen

synopsis:            Multimodal semantics in Text editing (command-line interface)
category:            Text

dependencies:
  - aeson              >= 1.3.1.1  && < 1.5
  - base               >= 4.11.1.0 && < 4.13
  - base64-bytestring  >= 1.0.0.1  && < 1.1
  - binary             >= 0.8.5.1  && < 0.9
  - bytestring         >= 0.10.8.2 && < 0.11
  - containers         >= 0.5.11.0 && < 0.7
  - exceptions         >= 0.10.0   && < 0.11
  - file-embed         >= 0.0.10.1 && < 0.1
  - filepath           >= 1.4.2    && < 1.5
  - mono-traversable   >= 1.0.9.0  && < 1.1
  - mtl                >= 2.2.2    && < 2.3
  - muste              >= 0.3.0    && < 0.4
  - pgf                >= 3.10     && < 3.11
  - prettyprinter      >= 1.2.1    && < 1.3
  - sqlite-simple      >= 0.4.16.0 && < 0.5
  - string-conversions >= 0.4.0.1  && < 0.5
  - template-haskell   >= 2.13.0.0 && < 2.15
  - text               >= 1.2.3.1  && < 1.3
  - tostring           >= 0.2.1.1  && < 0.3
  - array              >= 0.5.2.0  && < 0.6
  - vector             >= 0.12.0.1 && < 0.13
  - deepseq            >= 1.4.3.0  && < 1.5
  - multiset           >= 0.3.4    && < 0.4
  - directory          >= 1.3.1.5  && < 1.4
  - monad-control      >= 1.0.2.3  && < 1.1
  - transformers-base  >= 0.4.5.2  && < 0.5
  - snap               >= 1.1.2.0  && < 1.2
  - yaml               >= 0.8.32   && < 0.12
  - time               >= 1.8.0.2  && < 1.9
  - gitrev             >= 1.3.1    && < 1.4

executables:
  muste-cli:
    source-dirs:
      - src

    main: Main.hs

    other-modules:
      - Muste.Repl
      - Options

    dependencies:
      - muste
      - haskeline            >= 0.7.4.3  && < 0.8
      - repline              >= 0.2.0.0  && < 0.3
      - optparse-applicative >= 0.14.3.0 && < 0.15
