name:                muste-cli
version:             0.4.0
license:             BSD3
license-file:        LICENSE
maintainer:
  - Herbert Lange <herbert.lange@cse.gu.se>
  - Peter Ljunglöf <peter.ljunglof@cse.gu.se>
copyright:
  - (c) 2017-2019 Herbert Lange
  - (c) 2018-2019 Peter Ljunglöf
  - (c) 2018      Frederik Hanghøj Iversen

synopsis:            Multimodal semantics in Text editing (command-line interface)
category:            Text

source-dirs:
  - src/

dependencies:
  - base                 >= 4.11.1.0 && < 4.13
  - binary               >= 0.8.5.1  && < 0.9   # Data.Binary
  - containers           >= 0.5.11.0 && < 0.7   # Data.{Map, Set, Tree, ...}
  - gitrev               >= 1.3.1    && < 1.4   # Development.GitRev
  - haskeline            >= 0.7.4.3  && < 0.8   # System.Console.Haskeline
  - mono-traversable     >= 1.0.9.0  && < 1.1   # Data.{Containers, MonoTraversable, ...}
  - mtl                  >= 2.2.2    && < 2.3   # Control.Monad.{Except, Reader, State, Trans, ...}
  - muste                >= 0.4      && < 0.5   # Muste
  - optparse-applicative >= 0.14.3.0 && < 0.15  # Options.Applicative
  - prettyprinter        >= 1.2.1    && < 1.3   # Data.Text.Prettyprint
  - repline              >= 0.2.0.0  && < 0.3   # System.Console.Repline
  - text                 >= 1.2.3.1  && < 1.3   # Data.Text

executables:
  muste-cli:
    main: Main.hs

    other-modules:
      - Muste.Repl
      - Options
